use std::collections::HashSet;
use std::{fs, path::Path};

fn main() {
    // ----------------------------
    // 1. Rebuild triggers
    // ----------------------------
    println!("cargo:rerun-if-changed=resources/icons.gresource.xml");
    println!("cargo:rerun-if-changed=metadata.json");
    println!("cargo:rerun-if-changed=build.rs");

    // ----------------------------
    // 2. Compile GResource
    // ----------------------------
    glib_build_tools::compile_resources(
        &["resources"],                  // search path
        "resources/icons.gresource.xml", // XML
        "icons.gresource",               // output binary
    );

    // ----------------------------
    // 3. Generate Rust constants and code map from JSON
    // ----------------------------
    let json = fs::read_to_string("resources/metadata.json").expect("Failed to read metadata.json");
    let icons: Vec<Icon> = serde_json::from_str(&json).expect("Invalid metadata.json");
    generate_icons_rust(&icons).expect("Failed to generate Rust icons");
    generate_icons_codemap(&icons).expect("Failed to generate code map");
}

fn generate_icons_rust(icons: &[Icon]) -> std::io::Result<()> {
    // let json = fs::read_to_string("metadata.json")?;

    // let icons: Vec<Icon> = serde_json::from_str(&json).expect("Invalid metadata.json");

    let icons: HashSet<String> = icons.iter().map(|icon| icon.name.clone()).collect();

    let mut output = String::new();

    output.push_str("// @generated by build.rs — do not edit\n\n");

    for icon in icons {
        let const_name = icon.to_uppercase().replace("-", "_");

        output.push_str(&format!("pub const {}: &str = \"{}\";\n", const_name, icon));
    }

    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest = Path::new(&out_dir).join("icons.rs");

    fs::write(dest, output)?;

    Ok(())
}

fn generate_icons_codemap(icons: &[Icon]) -> std::io::Result<()> {
    use std::{fs, path::Path};

    let mut output = String::new();

    output.push_str("// @generated by build.rs — do not edit\n\n");
    output.push_str("use phf::phf_map;\n\n");

    output.push_str("pub static ICONS: phf::Map<char, &'static str> = phf_map! {\n");

    for icon in icons {
        let Some(code) = &icon.code else {
            continue;
        };

        let codepoint = u32::from_str_radix(code, 16).expect("Invalid codepoint");

        let _ch = char::from_u32(codepoint).expect("Invalid Unicode scalar value");

        output.push_str(&format!(
            "    '\\u{{{:X}}}' => \"{}\",\n",
            codepoint, icon.name
        ));
    }

    output.push_str("};\n");

    let out_dir = std::env::var("OUT_DIR").unwrap();
    fs::write(Path::new(&out_dir).join("codemap.rs"), output)?;

    Ok(())
}
// ----------------------------
// JSON model
// ----------------------------
#[derive(serde::Deserialize)]
struct Icon {
    code: Option<String>,
    name: String,
}
